apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: redis-batching-agent
  namespace: openwhisk
  labels:
    app: redis-batching-agent
spec:
  selector:
    matchLabels:
      app: redis-batching-agent
  template:
    metadata:
      labels:
        app: redis-batching-agent
    spec:
      containers:
      - name: redis-batching-agent
        image: localhost:5000/redis-batching-agent:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          hostPort: 8080  # Expose directly on the node at a fixed port
        env:
        - name: REDIS_HOST
          value: "redis-master"  # Replace with your actual Redis host
        - name: REDIS_PORT
          value: "6379"
        - name: BATCH_WINDOW
          value: "100ms"
        - name: MAX_BATCH_SIZE
          value: "10"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      hostNetwork: true  # Use host networking
      dnsPolicy: ClusterFirstWithHostNet 