apiVersion: v1
kind: Service
metadata:
  name: redis-batching-agent
  namespace: openwhisk
  labels:
    app: redis-batching-agent
spec:
  selector:
    app: redis-batching-agent
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP 