apiVersion: v1
kind: Service
metadata:
  name: redis-batching-agent
  namespace: openwhisk
  labels:
    app: redis-batching-agent
spec:
  selector:
    app: redis-batching-agent
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  # This is a headless service (no ClusterIP) allowing direct access to the pods
  clusterIP: None
  # We use headless service so containers can access the agent on their local node
  # This works together with hostNetwork: true in the DaemonSet 