apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openwhisk
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: openwhisk
subjects:
- kind: ServiceAccount
  name: default
  namespace: openwhisk
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

